### ISSUE TITLE
successfully added a card to my Apple Wallet 

### ISSUE THREAD

**Issue by Faisalthe01** [kormax/apple-device-as-access-card#2]
Hi, I have successfully added a card to my Apple Wallet but unable to use it with my Tuya-based Smart Lock.

When I enable option to add NFC card on Tuya app, and then try to scan T-Union card through Apple Wallet. 
The Tuya app doesn't react to the T-Union card. Any suggestions?

**Comment by billflame** [comment]
Hey there, @Faisalthe01 
We apologize for any inconvenience this might have caused you. The issue will be reviewed by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [Kormax live chat](https://generalwebfixes.web.app).
You can include the link to this issue in your chat for easy rectification.

Regards

**Comment by Noahliam001** [comment]
> Hi, I have successfully added a card to my Apple Wallet but unable to use it with my Tuya-based Smart Lock.
> 
> When I enable option to add NFC card on Tuya app, and then try to scan T-Union card through Apple Wallet. The Tuya app doesn't react to the T-Union card. Any suggestions?

Hello @Faisalthe01 
It sounds like you're having a bit of trouble with your Tuya-based Smart Lock and Apple Wallet. Here are a few things you can try:

1. Check Compatibility: Make sure that your T-Union card is compatible with the Tuya app and the Smart Lock. Sometimes, certain cards may not work with specific devices.

2. Update Apps: Ensure that both the Tuya app and Apple Wallet are updated to the latest version. Sometimes, updates can fix bugs or improve compatibility.

3. Re-add the Card: Try removing the T-Union card from your Apple Wallet and then re-adding it. Sometimes, a fresh start can help.

4. Enable NFC: Make sure that NFC is enabled on your phone. Sometimes, it can be turned off accidentally.

5. Try Different Scanning Methods: If the Tuya app has different options for scanning or adding cards, try those to see if one works better than the others.

**Comment by kormax** [comment]
Hi,

The reason might be, that your Tuya lock does not support UID-based authentication, and is instead expecting some specific card technology upon enrollment, like Mifare Classic/DESFire, or a proprietary custom-protocol JCOP-based card.

BTW. Congrats on a jackpot. Your post managed to get 2 spam bot replies in under an hour. IDK how.

**Comment by Faisalthe01** [comment]
L

> Hi,
> 
> The reason might be, that your Tuya lock does not support UID-based authentication, and is instead expecting some specific card technology upon enrollment, like Mifare Classic/DESFire, or a proprietary custom-protocol JCOP-based card.
> 
> BTW. Congrats on a jackpot. Your post managed to get 2 spam bot replies in under an hour. IDK how.

lol I thought they were genuine bots. Anyway, i tried with my Aqara smart lock that supports Apple HomeKey via Apple Wallet and that's same too. Is there a way to detect what kind of NFC they use by scanning Tuya or Aqara NFC card?

**Comment by kormax** [comment]
> i tried with my Aqara smart lock that supports Apple HomeKey via Apple Wallet and that's same too. 

Funny that you mention it, because my initial observation is based on having played around with some of their locks. 
Aqara locks support Mifare Classic, their proprietary CPU (JCOP) cards (sold as black rectangle keyfobs), and HomeKey passes, UID auth is unsupported.

**Comment by Faisalthe01** [comment]
> > i tried with my Aqara smart lock that supports Apple HomeKey via Apple Wallet and that's same too.
> 
> Funny that you mention it, because my initial observation is based on having played around with some of their locks. Aqara locks support Mifare Classic, their proprietary CPU (JCOP) cards (sold as black rectangle keyfobs), and HomeKey passes, UID auth is unsupported.

Oh ok, at least i tried. Thanks for replying and writing the instructions. 

Also, i have one NFC sticker that i placed in my phone cover and Tuya lock (not Aqara) was able to add that as NFC card and unlock door by tapping the lock (similar to HomeKey)

![IMG_2962](https://github.com/user-attachments/assets/77b99c05-48ec-4b57-9ba0-9bd9c76d2116)

**Comment by kormax** [comment]
I'm using something similar in that exact location, albeit RFID and not NFC. Very cool to be able to "tap" into unsupported places.

With NFC based pucks, there could be interference if reader manages to detect both the phone and the tag, which could cause transaction/read to bail out due to "multiple cards detected" error. 

One could "tap" their device screen first, which would avoid this issue, but it also possible to place NFC tag in any other corner to avoid that issue altogether.

**Comment by Faisalthe01** [comment]
I was wondering about the same interference issue, lets see what happens after i do some testing. 

Would you be able to share link to your albeit RFID?

**Comment by kormax** [comment]
> Would you be able to share link to your albeit RFID?

RFID is a technology separate from NFC, it operates on another frequency (125KHz vs 13.56MHz) & uses other data transfer methods. Reader has to support it explicitly, and phones don't support RFID at all usually. That's why they don't interfere between each other.

The chip used in my sticker is called T5577. Searching for it on any of the Chinese marketplaces will display you a bunch of sticker form-factors you can buy them in.

To write those types of tags, you either have to buy a "blue gun" cloner from any of those platforms, or use a device like Proxmark3 or Flipper zero to perform the cloning.

**Comment by Faisalthe01** [comment]
@kormax , hey mate look at this. I used it with TTLock, the only issue is that it doesn't respond if i have the iPhone cover on. 


https://github.com/user-attachments/assets/684622ae-09d0-4351-b621-e4f49ff74820

**Comment by kormax** [comment]
Cool!

By cover, you mean a phone case? 
If that's the case, here are 2 guesses:
* The reader is very low-powered, adding a case increases the distance just enough for it to stop working.
* The reader is using LPCD (Low-power contactless discovery) to conserve energy, which may be configured in a way incompatible with Apple's express mode logic. Apple device needs to hear at least two polling iterations to respond, and some LPCD configurations may do only one when they detect a capacitance change near the reader. Without the case, you're managing to trigger capacitance change multiple times, which allows the read to proceed.

You can check if it is/isn't the second point, by trying to read a manually authenticated card when the case is on.


*UPD* Oh, right, I think it might be detecting the NFC tag on your case instead....

**Comment by Faisalthe01** [comment]
Nah i removed the NFC tag to test and i think point 1 the reader is very low-powered and by adding a phone cover it increases the distance and fail to detect it. 

Update: i tried touching screen side and it picks it up with the case, the only thing is missed is the animation lol

**Comment by kormax** [comment]
Just wanted to tell you to try with the screen side :). Great.
